import "server-only";
import { createAdminClient } from "@/lib/supabase/admin";

// CATALOG-WRITE-AUTH-1: the ONE way a Server Action obtains authority to
// write the protected catalog columns of public.books and public.bundles
// (`status`, `price_all`, `published_at`) -- and, since
// CATALOG-STORAGE-PATH-AUTH-1 (migration 20260924141734), the storage
// paths `books.file_path` and `books.cover_path`, which `authenticated`
// may no longer insert.
//
// Since migration 20260924101853_catalog_write_authorization,
// `authenticated` can no longer write those columns directly: a session
// client, and therefore the Data API an author's browser can reach,
// holds INSERT only on the columns of a new draft and UPDATE only on
// books.series_id / books.series_position. The protected transitions
// (publish, unpublish, and an edit that carries a price) are decided in
// the Server Actions -- paid-publishing permission, repricing rule,
// ownership, maintenance and recovery -- and only then written through
// this client, which uses the server-only service-role key.
//
// Rules every caller follows, each pinned by
// src/app/(public)/dashboard/catalog-write-authorization.test.ts:
//
//   1. Authenticate with the session client first, and run every
//      rejecting gate and ownership read BEFORE calling this. A request
//      that is going to be refused never creates privileged authority.
//   2. Every UPDATE is filtered by BOTH the row id and
//      `author_id = <the authenticated user's id>`. This client bypasses
//      RLS, so those filters are the ownership boundary.
//      There is exactly ONE insert, and it is the audited exception:
//      createBook's new-book row. An insert has no row to filter, so its
//      boundary is its payload instead -- `author_id` is the authenticated
//      user's id, `id` is generated by the server, `file_path` and
//      `cover_path` are derived by the server from those two, `status` is
//      never named (the column default, 'draft', applies), and nothing in
//      it comes from a client-supplied id, author or path. No other insert
//      goes through this client.
//   3. Every write returns `.select("id")` and must prove exactly one row
//      changed (isExactlyOneRowWritten); the insert must also return the
//      id it generated. Zero or several rows fail closed.
//   4. Ordinary reads, uploads, deletes and the series unlink stay on the
//      least-privileged session client.
//
// `server-only` makes any import of this module from a client component
// a build error, so the key can never reach browser code through it.
export function createCatalogWriteClient() {
  return createAdminClient();
}
